steps:

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['test']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package', 'appengine:stage']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'target/appengine-staging/app.yaml','--project','$PROJECT_ID'] 
